services:
  radar-punto:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=radar_punto
      - DB_POSTGRESDB_USER=radar_user
      - DB_POSTGRESDB_PASSWORD=radar_pass
      - N8N_ENCRYPTION_KEY=d9bdce8090778db64c977aef79f25340ebd5031a104965d8515e4e5aa3e930c3
