[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "n8n"

[services.variables]
N8N_HOST = "0.0.0.0"
N8N_PORT = "3000"
N8N_PROTOCOL = "https"
GENERIC_TIMEZONE = "America/Sao_Paulo"
TZ = "America/Sao_Paulo"
NODE_ENV = "production"

# Database configs (será preenchido após criar PostgreSQL)
DB_TYPE = "postgresdb"
DB_POSTGRESDB_HOST = "${PGHOST}"
DB_POSTGRESDB_PORT = "${PGPORT}"
DB_POSTGRESDB_DATABASE = "${PGDATABASE}"
DB_POSTGRESDB_USER = "${PGUSER}"
DB_POSTGRESDB_PASSWORD = "${PGPASSWORD}"

# Encryption key (IMPORTANTE: gerar uma chave única - veja instruções abaixo)
N8N_ENCRYPTION_KEY = "SUBSTITUA-POR-UMA-CHAVE-DE-32-CARACTERES"

# Configurações de webhook
WEBHOOK_URL = "https://monitoria-cerc-railway-production.railway.app/"
N8N_EDITOR_BASE_URL = "https://monitoria-cerc-railway-production.railway.app/"
