[build]
builder = "dockerfile"

[deploy]
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "radar-punto"

[services.variables]
N8N_HOST = "0.0.0.0"
N8N_PORT = "3000"
N8N_PROTOCOL = "https"
GENERIC_TIMEZONE = "America/Sao_Paulo"
TZ = "America/Sao_Paulo"
NODE_ENV = "production"

# Database configs (conectar via Railway Variables)
DB_TYPE = "postgresdb"
DB_POSTGRESDB_HOST = "${PGHOST}"
DB_POSTGRESDB_PORT = "${PGPORT}"
DB_POSTGRESDB_DATABASE = "${PGDATABASE}"
DB_POSTGRESDB_USER = "${PGUSER}"
DB_POSTGRESDB_PASSWORD = "${PGPASSWORD}"

# Encryption key
N8N_ENCRYPTION_KEY = "c4ef1c4c0fe74fcf350e2206d80ea2092bdb978457a42053164ae6505fe8a3b4"

# URLs (ajustar conforme deploy)
WEBHOOK_URL = "${WEBHOOK_URL}"
N8N_EDITOR_BASE_URL = "${N8N_EDITOR_BASE_URL}"
